id: P007863
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS19329
  title: གསུང་འབུམ། རིག་འཛིན་གར་གྱི་དབང་ཕྱུག
  author: ''
  volumes:
    31ed8ba72bfc407d8114341460fc0aef:
      image_group_id: I8LS19331
      title: Volume 1 of them byang rgyud skar phreng ba phan bde legs tshogs kun
        'byung nam mkha'i mdzod chen/
      volume_number: 1
      total_pages: 600
      base_file: v001.txt
ebook_metadata:
  title: གསུང་འབུམ། རིག་འཛིན་གར་གྱི་དབང་ཕྱུག
  author: ''
  sku: P007863
  cover: cover.jpg
  layers:
  - pagination
