id: P007863
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS19329
  title: གསུང་འབུམ། རིག་འཛིན་གར་གྱི་དབང་ཕྱུག
  author: ''
  volumes:
    a35034964a6b4204ba9bd7d24fbee29b:
      image_group_id: I8LS19331
      title: ''
      volume_number: 1
      total_pages: 600
ebook_metadata:
  title: གསུང་འབུམ། རིག་འཛིན་གར་གྱི་དབང་ཕྱུག
  author: ''
  sku: P007863
  cover: cover.jpg
  layers:
  - pagination
